### ISSUE TITLE
Consider using TypeBox

### ISSUE THREAD

**Issue by gabewillen** [iann838/apertum#1]
This library looks promising I would suggest using TypeBox over Zod. Zod issues keep climbing and it hasn't seen a release since last October. TypeBox preforms better and is extremely flexible in its decoder / encoder integrations.  Just my opinion either way keep up the great work!

**Comment by iann838** [comment]
@gabewillen Thanks! Unfortunately, this library requires converting types to openapi schemas, and looks like typebox does not have that, at first, [openapi-box](https://github.com/geut/openapi-box) seems to be the deal, but after carefully reviewing it, it only works the other way around. If you do find the equivalent of [zod-to-openapi](https://github.com/asteasolutions/zod-to-openapi), I would be happy to find way to support it.

**Comment by iann838** [comment]
I will be closing this issue as there is no more progress
